name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge Pull Request
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the PAT token instead of the default one
        with:
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: "squash"
            });

